#!/bin/bash

#This file is part of arcasHLA.
#
#    arcasHLA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    arcasHLA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with arcasHLA.  If not, see <https://www.gnu.org/licenses/>.

#-----------------------------------------------------------------------------

if [ "$1" == "extract" ]; then

    python ./scripts/extract.py ${@:2}

elif [ "$1" == "genotype" ]; then

    python ./scripts/genotype.py ${@:2}

elif [ "$1" == "table" ]; then

    python ./scripts/table.py ${@:2}

elif [ "$1" == "reference" ]; then

    python ./scripts/build_reference.py ${@:2}

elif [ "$1" == "partial" ]; then

    python ./scripts/partial.py ${@:2}

else
    echo
    echo "Usage: arcasHLA <command> [options]"
    echo
    echo "    extract        extracts chromosome 6 reads from bam"
    echo "    genotype       types HLA genes from extracted reads"
    echo "    partial        types partial HLA alleles from extracted reads"
    echo "    table          processes results into a tab-separated table"
    echo "    reference      check or update HLA reference"
    echo
    echo "Note: run any command with --help to view required fields, options"
    echo
fi

#-------------------------------------------------------------------------------
